language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
script: nosetests -s -v --with-coverage --cover-package=rib
after_success:
  - coveralls
